name: Contract workflow

on:
  push:
    branches: ["**"]
    paths:
      - "crowdfund/contracts/**.sol"
      - "crowdfund/test/**.js"

env:
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

defaults:
  run:
    working-directory: crowdfund

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version-file: crowdfund/.nvmrc

      - name: Install
        run: |
          npm install

      - name: Compile
        run: |
          npx hardhat compile

      - name: Test
        run: |
          npx hardhat test

      - name: Lint
        run: |
          npm run lint
